from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('registros/', views.listarRegistro, name='registros'),
    path('programaciones/', views.listarProgramaciones, name='programaciones'),
    path('turnos/', views.listarTurnos, name='turnos'),
    path('justificaciones/', views.listarJustificaciones, name='justificaciones'),
    path('registros/<int:id_registro>/',
         views.detalleRegistro, name='registro_detalle'),
    path('programaciones/<int:id_turno_programado>/',
         views.detalleProgramacion, name='turno_programacion_detalle'),
    path('turnos/<id_turno>/', views.detalleTurnos, name='turno_detalle'),
    path('justificaciones/<id_justificacion>/',
         views.detalleJustificaciones, name='justificacion_detalle'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('crearRegistro/', views.crearRegistro, name='crear_registro'),
    path('crearProgramacion/', views.crearProgramacion, name='crear_programacion'),
    path('crearTurno/', views.crearTurno, name='crear_turno'),
    path('crearJustificacion/', views.crearJustificacion,
         name='crear_justificacion'),
    path('buscarFecha/', views.buscarFechaPorRango, name='buscar_rango_fecha'),
    path('busquedaEmpleado/', views.buscarEmpleado, name='buscar_empleado'),
    path('programacionesFecha/', views.buscarTurnoFecha,
         name='buscar_turnos_fecha'),
    path('programacionesEmpleado/', views.buscarTurnoEmpleado,
         name='buscar_turnos_empleado'),
    path('cargarTurnosProgramados/', views.cargarProgramacionTurnos,
         name='cargar_turnos_programados'),
    path('cargarRegistros/', views.cargarRegistros, name='cargar_registros'),
    path('exportarRegistrosFechaExcel/', views.exportarDatosRangoFechaExcel,
         name='exportar_registros_fecha_excel'),
    path('exportarRegistrosEmpleadoExcel/',
         views.exportarDatosEmpFechaExcel, name='exportar_registros_emp_excel'),
    path('exportarTurnosFechaExcel/', views.exportarTurnosRangoFechaExcel,
         name='exportar_turnos_fecha_excel'),
    path('exportarTurnosEmpleadoExcel/', views.exportarTurnosEmpFechaExcel,
         name='exportar_turnos_emp_excel'),
    path('turnosProgramados/<empleado_id>',
         views.get_turnos_programados, name='get_turnos_programados'),
]
