# Generated by Django 4.2.4 on 2023-08-31 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentrosCostos',
            fields=[
                ('id_centro', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ID Centro de Costo')),
                ('descripcion_centro', models.CharField(max_length=50, verbose_name='Descripción Centro de Costos')),
            ],
            options={
                'verbose_name': 'Centro de Costos',
                'verbose_name_plural': 'Centros de Costos',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=70, verbose_name='Departamento')),
                ('descripcion_departamento', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Documento')),
                ('nombre_empleado', models.CharField(max_length=120, verbose_name='Nombre')),
                ('apellido_paterno_empleado', models.CharField(max_length=70, verbose_name='Primer apellido')),
                ('apellido_materno_empleado', models.CharField(blank=True, max_length=70, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento_empleado', models.DateField(verbose_name='Fecha Nacimiento')),
                ('sexo_empleado', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('NB', 'No Binario')], max_length=2, verbose_name='Sexo/Genero')),
                ('telefono_empleado', models.CharField(blank=True, max_length=11, null=True, verbose_name='Teléfono')),
                ('email_empleado', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, verbose_name='Estado Empleado')),
                ('fecha_ingreso_empleado', models.DateField(verbose_name='Fecha Ingreso')),
                ('fecha_baja_empleado', models.DateField(blank=True, null=True, verbose_name='Fecha Salida')),
                ('fecha_reingreso_empleado', models.DateField(blank=True, null=True, verbose_name='Fecha Reingreso')),
                ('centro_costo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pyturnos.centroscostos', verbose_name='Centro de Costos')),
                ('departamento_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyturnos.departamentos', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='GruposEmpleados',
            fields=[
                ('id_grupo_emp', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_grupo', models.CharField(max_length=50, verbose_name='Descripcion Grupo Empleados')),
            ],
            options={
                'verbose_name': 'Grupo Empleados',
                'verbose_name_plural': 'Grupos Empleados',
            },
        ),
        migrations.CreateModel(
            name='Justificaciones',
            fields=[
                ('id_justificacion', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion_justificacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Justificación',
                'verbose_name_plural': 'Justificaciones',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('tipo_turno', models.CharField(blank=True, choices=[('ADM', 'Administrativo'), ('AST', 'Asistencial')], max_length=3, null=True, verbose_name='Tipo Turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='TurnosProgramados',
            fields=[
                ('id_turno_programado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_turno', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyturnos.empleados', verbose_name='Empleado')),
                ('justificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyturnos.justificaciones', verbose_name='Justificación')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyturnos.turnos', verbose_name='Turno a Programar')),
            ],
            options={
                'verbose_name': 'Turno Programado',
                'verbose_name_plural': 'Turnos Programados',
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('fecha_registro_entrada', models.DateField(blank=True, null=True)),
                ('hora_registro_entrada', models.TimeField(blank=True, null=True)),
                ('fecha_registro_salida', models.DateField(blank=True, null=True)),
                ('hora_registro_salida', models.TimeField(blank=True, null=True)),
                ('obs_marcacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marcación')),
                ('obs_entrada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Entrada')),
                ('obs_salida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Salida')),
                ('analisis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Análisis')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyturnos.empleados', verbose_name='Empleado')),
                ('justificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyturnos.justificaciones', verbose_name='Justificacion')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyturnos.turnos', verbose_name='Turno')),
                ('turno_programado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyturnos.turnosprogramados', verbose_name='Turno Programado')),
            ],
        ),
        migrations.AddField(
            model_name='centroscostos',
            name='grupo_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyturnos.gruposempleados', verbose_name='Grupo Empleados'),
        ),
    ]
