# Generated by Django 4.2.4 on 2023-08-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyturnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registros',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterField(
            model_name='empleados',
            name='sexo_empleado',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario')], max_length=2, verbose_name='Sexo/Genero'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registros',
            name='justificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyturnos.justificaciones', verbose_name='Justificacion'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='tipo_turno',
            field=models.CharField(blank=True, choices=[('ADM', 'Administrativo'), ('24H', 'Día Completo'), ('AST', 'Asistencial')], max_length=3, null=True, verbose_name='Tipo Turno'),
        ),
    ]
