# Generated by Django 4.2.4 on 2023-09-04 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('pyturnos', '0003_alter_empleados_sexo_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.CharField(choices=[('I', 'Inactivo'), ('A', 'Activo')], max_length=1, verbose_name='Estado Empleado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='sexo_empleado',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario')], max_length=2, verbose_name='Sexo/Genero'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='turno_programado',
            field=models.ForeignKey(limit_choices_to={'empleado': django.db.models.expressions.OuterRef('empleado')}, on_delete=django.db.models.deletion.CASCADE, to='pyturnos.turnosprogramados', verbose_name='Turno Programado'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='tipo_turno',
            field=models.CharField(blank=True, choices=[('24H', 'Día Completo'), ('ADM', 'Administrativo'), ('AST', 'Asistencial')], max_length=3, null=True, verbose_name='Tipo Turno'),
        ),
    ]
