# Generated by Django 4.2.4 on 2023-09-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyturnos', '0004_alter_empleados_estado_alter_empleados_sexo_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, verbose_name='Estado Empleado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='sexo_empleado',
            field=models.CharField(choices=[('M', 'Masculino'), ('NB', 'No Binario'), ('F', 'Femenino')], max_length=2, verbose_name='Sexo/Genero'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='turno_programado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyturnos.turnosprogramados', verbose_name='Turno Programado'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='tipo_turno',
            field=models.CharField(blank=True, choices=[('ADM', 'Administrativo'), ('24H', 'Día Completo'), ('AST', 'Asistencial')], max_length=3, null=True, verbose_name='Tipo Turno'),
        ),
    ]
