# Generated by Django 4.2.4 on 2023-09-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyturnos', '0005_alter_empleados_estado_alter_empleados_sexo_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='sexo_empleado',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('NB', 'No Binario')], max_length=2, verbose_name='Sexo/Genero'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='tipo_turno',
            field=models.CharField(blank=True, choices=[('ADM', 'Administrativo'), ('AST', 'Asistencial'), ('24H', 'Día Completo')], max_length=3, null=True, verbose_name='Tipo Turno'),
        ),
    ]
