# Generated by Django 4.2.4 on 2023-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyturnos', '0011_alter_empleados_sexo_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.CharField(choices=[('I', 'Inactivo'), ('A', 'Activo')], max_length=1, verbose_name='Estado Empleado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='sexo_empleado',
            field=models.CharField(choices=[('NB', 'No Binario'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=2, verbose_name='Sexo/Genero'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='tipo_turno',
            field=models.CharField(blank=True, choices=[('AST', 'Asistencial'), ('ADM', 'Administrativo'), ('24H', 'Día Completo')], max_length=3, null=True, verbose_name='Tipo Turno'),
        ),
    ]
